# Generated by Django 3.2.7 on 2021-10-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('access_token', models.CharField(default=None, max_length=500)),
                ('owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('x_coordinates', models.FloatField()),
                ('y_coordinates', models.FloatField()),
                ('notes', models.CharField(max_length=500)),
                ('trip_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.trip')),
            ],
        ),
    ]
